# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right_under2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_right_under2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_leg_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rear_leg_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left_under2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_left_under2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_leg_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rear_leg_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left_under] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_left_under set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right_under] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_right_under set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_leg_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rear_body set from storage animated_java:gu out