# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.animal_omega.animation.skill.playing
tag @s remove aj.animal_omega.animation.death.playing
tag @s remove aj.animal_omega.animation.ready.playing
tag @s remove aj.animal_omega.animation.move.playing
tag @s remove aj.animal_omega.animation.attack.playing