# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_wolf.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_wolf', 'function_path': 'animated_java:animal_wolf/animations/ready/stop'}
tag @s remove aj.animal_wolf.animation.ready.playing
scoreboard players set @s aj.ready.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:animal_wolf/animations/ready/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only