# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_bear.root] run return 0
execute on passengers if entity @s[tag=aj.animal_bear.data] unless data entity @s {data:{rigHash: 'caf4dc9fed2f964024db47bc76731644aea2d7423962c6b5d82c3ace33a9454e'}} on vehicle run function animated_java:animal_bear/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1