# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_alpha.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_alpha', 'function_path': 'animated_java:animal_alpha/animations/pause_all'}
tag @s remove aj.animal_alpha.animation.skill.playing
tag @s remove aj.animal_alpha.animation.death.playing
tag @s remove aj.animal_alpha.animation.ready.playing
tag @s remove aj.animal_alpha.animation.move.playing
tag @s remove aj.animal_alpha.animation.attack.playing