# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_rear_leg_right_under) {transformation: [-1f,0f,0f,0.4688f,0f,1f,0f,-1f,0f,0f,-1f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_left) {transformation: [-1f,0f,0f,0.4688f,0f,1f,0f,-0.3437f,0f,0f,-1f,-0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg_left_under) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1f,0f,0f,-1f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_right) {transformation: [-1f,0f,0f,-0.4687f,0f,1f,0f,-0.3437f,0f,0f,-1f,-0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tale) {transformation: [-1.3229f,0f,0f,0f,0f,1.3179f,0.1153f,-0.0391f,0f,0.1153f,-1.3179f,-1.3828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_body) {transformation: [-1.1719f,0f,0f,0f,0f,1.1719f,0f,-0.3672f,0f,0f,-1.1719f,0.3516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0156f,0f,0.9979f,-0.0654f,0.1302f,0f,-0.0654f,-0.9979f,1.255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_talon_left) {transformation: [-1.0104f,0f,0f,0.6152f,0f,0.9588f,-0.3189f,-1.4926f,0f,-0.3189f,-0.9588f,0.6096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under) {transformation: [-1f,0f,0f,0.6006f,0f,0.9469f,-0.3214f,-1.0393f,0f,-0.3214f,-0.9469f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left) {transformation: [-1f,0f,0f,0.5625f,0f,0.9808f,0.1951f,-0.3671f,0f,0.1951f,-0.9808f,0.4711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_talon_right) {transformation: [-1.0104f,0f,0f,-0.6299f,0f,0.9588f,-0.3189f,-1.4634f,0f,-0.3189f,-0.9588f,0.6134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right_under) {transformation: [-1f,0f,0f,-0.5625f,0f,0.9469f,-0.3214f,-1.029f,0f,-0.3214f,-0.9469f,0.435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right) {transformation: [-1f,0f,0f,-0.5625f,0f,0.9808f,0.1951f,-0.3671f,0f,0.1951f,-0.9808f,0.4711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_body) {transformation: [-1f,0f,0f,0f,0f,0.9808f,0.1951f,-0.3672f,0f,0.1951f,-0.9808f,0.3516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}