# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_rear_leg_right_under) {transformation: [-1f,0f,0f,0.4688f,0f,1f,0f,-1.2187f,0f,0f,-1f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_left) {transformation: [-1f,0f,0f,0.4688f,0f,1f,0f,-0.5625f,0f,0f,-1f,-0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg_left_under) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2187f,0f,0f,-1f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_right) {transformation: [-1f,0f,0f,-0.4687f,0f,1f,0f,-0.5625f,0f,0f,-1f,-0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tale) {transformation: [-1.3229f,0f,0f,0f,0f,1.3229f,0f,-0.2578f,0f,0f,-1.3229f,-1.3828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_body) {transformation: [-1.1719f,0f,0f,0f,0f,1.1719f,0f,-0.5859f,0f,0f,-1.1719f,0.3516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,-0.0156f,0f,1f,0f,0.0781f,0f,0f,-1f,1.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_talon_left) {transformation: [-1.0104f,0f,0f,0.6152f,0f,1.0104f,0f,-1.6875f,0f,0f,-1.0104f,0.5859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under) {transformation: [-1f,0f,0f,0.6006f,0f,1f,0f,-1.2187f,0f,0f,-1f,0.6152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left) {transformation: [-1f,0f,0f,0.5625f,0f,1f,0f,-0.5625f,0f,0f,-1f,0.4688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_talon_right) {transformation: [-1.0104f,0f,0f,-0.6299f,0f,1.0104f,0f,-1.6875f,0f,0f,-1.0104f,0.5918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right_under) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2187f,0f,0f,-1f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-0.5625f,0f,0f,-1f,0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5859f,0f,0f,-1f,0.3516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}