plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
}

group = 'eternal_return'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {

    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'

    //코틀린 스탠다드 라이브러리
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.0"

    implementation "it.unimi.dsi:fastutil:8.5.15"
    implementation 'com.google.code.gson:gson:2.10.1'
}

def targetJavaVersion = 21
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

kotlin {
    jvmToolchain(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

jar{
    archiveFileName = 'eternal_return.jar'
    destinationDirectory = file("E:\\다운로드\\paper 1.21.11\\plugins")
    manifest{
        attributes 'Main-Class': 'eternal_return.system.PluginInstance'
    }
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
