# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:animal_omega rig_hash set value 'a69a18927562786c0acf627eaa852e7311eca5e89e8873bc14ac1c0c26b33d19'
scoreboard objectives add aj.skill.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.ready.frame dummy
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.attack.frame dummy