# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_alpha.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_alpha', 'function_path': 'animated_java:animal_alpha/animations/ready/next_frame'}
execute if score @s aj.ready.frame matches 41.. run scoreboard players set @s aj.ready.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.ready.frame
execute at @s run function animated_java:animal_alpha/animations/ready/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.ready.frame 1