# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:animal_alpha/animations/pause_all
tag @s add aj.animal_alpha.animation.ready.playing
scoreboard players set @s aj.ready.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:animal_alpha/animations/ready/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only