# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '991fc26490f16ced51b7e95cb1ef2787b6700e525ec8ee445bb824cfbe3422ee'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack