# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '13f2d2e7f04758768b0482a162d4d4bfb36a45a32a7d4c875433a10c6f13cd42'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack