# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_alpha.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_alpha', 'function_path': 'animated_java:animal_alpha/animations/death/set_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.death.frame $(frame)
execute at @s run function animated_java:animal_alpha/animations/death/zzz/set_frame with storage aj:temp