# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_boar.root] run return 0
execute on passengers if entity @s[tag=aj.animal_boar.data] unless data entity @s {data:{rigHash: '7109aef1f38440c2217a9199f9c9717086a567ce95f04904367ccfa8c7ab9381'}} on vehicle run function animated_java:animal_boar/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1