
on load:
    set {server.starttime} to now

function broadcastChat(msg: text):
    set {_diff} to difference between now and {server.starttime}
    set {_sec} to floor({_diff} / 1 second)
    set {_min} to floor({_sec} / 60)
    set {_s} to mod({_sec}, 60)

    if {_s} < 10:
        set {_s} to "0%{_s}%"
    if {_min} < 10:
        set {_min} to "0%{_min}%"

    broadcast "&6[%{_min}%:%{_s}%] %{_msg}%"



on chat:
    cancel event
    
    set {_diff} to difference between now and {server.starttime}
    set {_sec} to floor({_diff} / 1 second)
    set {_min} to floor({_sec} / 60)
    set {_s} to mod({_sec},60)
    
    if {_s} < 10:
        set {_s} to "0%{_s}%"
    if {_min} < 10:
        set {_min} to "0%{_min}%"
    
    send "베타테스트 기간 동안 채팅기능을 지원하지 않습니다" to player
    #broadcast "&x&3&f&c&9&c&7[%{_min}%:%{_s}%] [%player%] &7: %message%"

on join:
    set join message to ""

on quit:
    set quit message to ""


## 플레이어 정보 설정
options:
    kd-prefix-color: &7
    kd-bracket-color: &8
    kd-number-color: &e
    # 이름 색상 설정
    name-color: &f

function updateKD(p: player):
    set {_uuid} to uuid of {_p}
    # 1. 킬/데스 변수 초기화
    #getPlayerScoreState({_p})
    if {kill::%{_uuid}%} is not set:
        set {kill::%{_uuid}%} to 0
    if {death::%{_uuid}%} is not set:
        set {death::%{_uuid}%} to 0
    
    # 2. 플레이어 번호 부여 (처음 접속 시)
    if {player_num::%{_uuid}%} is not set:
        add 1 to {total_player_count}
        set {player_num::%{_uuid}%} to {total_player_count}
        # 관리용으로 실제 이름 기록
        set {realname::%{_uuid}%} to name of {_p}
    

    set {_k} to {kill::%{_uuid}%} ? "5"
    set {_d} to {death::%{_uuid}%} ? "0"
    set {_n} to {player_num::%{_uuid}%}
    
    # 3. 탭 리스트 이름 업데이트 (K/D + Player 번호)
    # 형식: [킬/데스] Player 번호
    set tab list name of {_p} to "&f[&e%{_k}%&f/&c%{_d}%&f] {@name-color}Player %{_n}%"
    
    # 4. (선택 사항) 채팅창 이름도 Player 번호로 변경
    set {_p}'s display name to "{@name-color}Player %{_n}%"

on join:
    wait 1 tick
    updateKD(player)
    
every 1 ticks:
    loop all players:
        wait 1 tick
        updateKD(loop-player)
