# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:animal_wolf rig_hash set value '13f2d2e7f04758768b0482a162d4d4bfb36a45a32a7d4c875433a10c6f13cd42'
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.ready.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.skill.frame dummy