# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.move.frame
scoreboard objectives remove aj.ready.frame
scoreboard objectives remove aj.death.frame
scoreboard objectives remove aj.attack.frame
scoreboard objectives remove aj.skill.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:animal_wolf)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'animal_wolf'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']