# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.llegdown] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_llegdown set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.lleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.rlegdown] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rlegdown set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.rleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.lknife] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lknife set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.larmdown] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_larmdown set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.larm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_larm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.rknife] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rknife set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.rarmdown] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rarmdown set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.rarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.upperbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upperbody set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.downbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_downbody set from storage aj:uuid main.out