# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:animal_boar rig_hash set value '09e35450118a934e422ac6258cead62d70bcfd05b68e73b914cfc3c32c56b696'
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.ready.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.skill.frame dummy