# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.rear_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rear_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.front_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_left_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_leg_left_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.rear_leg_right_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rear_leg_right_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.rear_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rear_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_right_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_leg_right_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.right_leg_left_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg_left_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.right_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_boar.bone.tale] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tale set from storage aj:uuid main.out