# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_omega.root] run return 0
execute if entity @s[tag=aj.animal_omega.animation.skill.playing] run function animated_java:animal_omega/animations/skill/zzz/on_tick
execute if entity @s[tag=aj.animal_omega.animation.death.playing] run function animated_java:animal_omega/animations/death/zzz/on_tick
execute if entity @s[tag=aj.animal_omega.animation.ready.playing] run function animated_java:animal_omega/animations/ready/zzz/on_tick
execute if entity @s[tag=aj.animal_omega.animation.move.playing] run function animated_java:animal_omega/animations/move/zzz/on_tick
execute if entity @s[tag=aj.animal_omega.animation.attack.playing] run function animated_java:animal_omega/animations/attack/zzz/on_tick
execute on passengers run rotate @s ~ ~