# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:animal_bear rig_hash set value '991fc26490f16ced51b7e95cb1ef2787b6700e525ec8ee445bb824cfbe3422ee'
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.ready.frame dummy
scoreboard objectives add aj.skill.frame dummy