# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_boar.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_boar', 'function_path': 'animated_java:animal_boar/animations/move/next_frame'}
execute if score @s aj.move.frame matches 13.. run scoreboard players set @s aj.move.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.move.frame
execute at @s run function animated_java:animal_boar/animations/move/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.move.frame 1