# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:animal_alpha rig_hash set value 'd523830ac178e51279f49d4483e206c3adbd3dc2fa673ba3d20afa24e3874393'
scoreboard objectives add aj.skill.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.ready.frame dummy
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.attack.frame dummy