# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:animal_bear/animations/move/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.move.frame 1