# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_front_leg_right_under2) {transformation: [-1f,0f,0f,-0.9178f,0f,0.5f,0.866f,-1.7144f,0f,0.866f,-0.5f,-1.9594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_right) {transformation: [-1f,0f,0f,-0.8675f,0f,0.866f,0.5f,-0.8675f,0f,0.5f,-0.866f,-1.6937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under2) {transformation: [-1f,0f,0f,0.9178f,0f,0.5f,0.866f,-1.7144f,0f,0.866f,-0.5f,-1.9594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_left) {transformation: [-1f,0f,0f,0.8675f,0f,0.866f,0.5f,-0.8675f,0f,0.5f,-0.866f,-1.6937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.9202f,0f,0f,-1f,0.9824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under) {transformation: [-1f,0f,0f,1.1678f,0f,0.5f,-0.866f,-1.5835f,0f,-0.866f,-0.5f,1.1736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left) {transformation: [-1f,0f,0f,0.9925f,0f,0.866f,-0.5f,-0.8675f,0f,-0.5f,-0.866f,0.6813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right_under) {transformation: [-1f,0f,0f,-1.2707f,0f,0.5f,-0.866f,-1.5951f,0f,-0.866f,-0.5f,1.0944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right) {transformation: [-1f,0f,0f,-1.1175f,0f,0.866f,-0.5f,-0.8675f,0f,-0.5f,-0.866f,0.6812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_body) {transformation: [-2.2812f,0f,0f,-0.0625f,0f,2.2813f,0f,-0.4996f,0f,0f,-2.2812f,-0.6609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_body) {transformation: [-1f,0f,0f,0.0156f,0f,1f,0f,-0.9758f,0f,0f,-1f,-1.5203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}