# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd523830ac178e51279f49d4483e206c3adbd3dc2fa673ba3d20afa24e3874393'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack