# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-0.8125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.8125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,-1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_down_arm) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,-0.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,-0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,-1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_down_arm2) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,-0.5f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm2) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.0625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upperbody) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.3125f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_downbody) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}