# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_wolf.root] run return 0
execute on passengers if entity @s[tag=aj.animal_wolf.data] unless data entity @s {data:{rigHash: '13450a93f755e0185fdf5c6699ecb250d7557b3c25d05a5cb4f1d480f2c5753e'}} on vehicle run function animated_java:animal_wolf/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1