# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_wolf.root] run return 0
execute if entity @s[tag=aj.animal_wolf.animation.move.playing] run function animated_java:animal_wolf/animations/move/zzz/on_tick
execute if entity @s[tag=aj.animal_wolf.animation.ready.playing] run function animated_java:animal_wolf/animations/ready/zzz/on_tick
execute if entity @s[tag=aj.animal_wolf.animation.death.playing] run function animated_java:animal_wolf/animations/death/zzz/on_tick
execute if entity @s[tag=aj.animal_wolf.animation.attack.playing] run function animated_java:animal_wolf/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.animal_wolf.animation.skill.playing] run function animated_java:animal_wolf/animations/skill/zzz/on_tick
execute on passengers run rotate @s ~ ~