# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a69a18927562786c0acf627eaa852e7311eca5e89e8873bc14ac1c0c26b33d19'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack