# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_front_leg_right_under2) {transformation: [-1f,0f,0f,-0.9178f,0f,1f,0f,-1.1196f,0f,0f,-1f,-1.5304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_right) {transformation: [-1f,0f,0f,-0.8675f,0f,1f,0f,-0.2533f,0f,0f,-1f,-1.7238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under2) {transformation: [-1f,0f,0f,0.9178f,0f,1f,0f,-1.1196f,0f,0f,-1f,-1.5304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_leg_left) {transformation: [-1f,0f,0f,0.8675f,0f,1f,0f,-0.2533f,0f,0f,-1f,-1.7238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.979f,0.2039f,1.3395f,0f,0.2039f,-0.979f,0.4274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left_under) {transformation: [-1f,0f,0f,1.1678f,0f,-0.5f,-0.866f,1.6896f,0f,-0.866f,0.5f,0.8727f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_left) {transformation: [-1f,0f,0f,0.9925f,0f,-0.5f,-0.866f,1.1973f,0f,-0.866f,0.5f,0.1567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right_under) {transformation: [-1f,0f,0f,-1.2707f,0f,-0.5351f,-0.8448f,1.64f,0f,-0.8448f,0.5351f,0.8667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_leg_right) {transformation: [-1f,0f,0f,-1.1175f,0f,-0.5351f,-0.8448f,1.1973f,0f,-0.8448f,0.5351f,0.1567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front_body) {transformation: [-2.2812f,0f,0f,-0.0625f,0f,1.8063f,-1.3934f,0.6688f,0f,-1.3934f,-1.8063f,-1.1307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rear_body) {transformation: [-1f,0f,0f,0.0156f,0f,0.7918f,-0.6108f,-0.2331f,0f,-0.6108f,-0.7918f,-1.5203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}