# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_alpha.root] run return 0
execute on passengers if entity @s[tag=aj.animal_alpha.data] unless data entity @s {data:{rigHash: 'e4ed1b9b233c29bcb7a317b9e6d0ba85d9cf3cd7a370b8021bc1bd31fc18743c'}} on vehicle run function animated_java:animal_alpha/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1