# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_alpha.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:animal_alpha/as_root/pre_tick
execute if entity @s[tag=aj.animal_alpha.animation.skill.playing] run function animated_java:animal_alpha/animations/skill/zzz/on_tick
execute if entity @s[tag=aj.animal_alpha.animation.death.playing] run function animated_java:animal_alpha/animations/death/zzz/on_tick
execute if entity @s[tag=aj.animal_alpha.animation.ready.playing] run function animated_java:animal_alpha/animations/ready/zzz/on_tick
execute if entity @s[tag=aj.animal_alpha.animation.move.playing] run function animated_java:animal_alpha/animations/move/zzz/on_tick
execute if entity @s[tag=aj.animal_alpha.animation.attack.playing] run function animated_java:animal_alpha/animations/attack/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:animal_alpha/as_root/post_tick