# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.animal_boar.animation.move.playing
tag @s remove aj.animal_boar.animation.ready.playing
tag @s remove aj.animal_boar.animation.death.playing
tag @s remove aj.animal_boar.animation.attack.playing
tag @s remove aj.animal_boar.animation.skill.playing