# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_boar.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_boar', 'function_path': 'animated_java:animal_boar/remove/this'}
function #animated_java:animal_boar/as_root/on_remove
execute on passengers run kill @s
kill @s