# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '09e35450118a934e422ac6258cead62d70bcfd05b68e73b914cfc3c32c56b696'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack